# This file was generated by GoReleaser. DO NOT EDIT.
cask "magmux" do
  version "0.13.0"

  on_macos do
    on_arm do
      sha256 "28c3ade31fcac04741d8ef7b203547ba506389940cac00e13bbc01da1006f4d8"
      url "https://github.com/MadAppGang/magmux/releases/download/v#{version}/magmux_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "68a775de2e8856813c17755e0b77ed986753176feb5ad00ab7f111b5a80711d5"
      url "https://github.com/MadAppGang/magmux/releases/download/v#{version}/magmux_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0b2b7e65d329b83f189e7978ee66062073e07cccd1a913dace475061ab78c806"
      url "https://github.com/MadAppGang/magmux/releases/download/v#{version}/magmux_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4d1b996e94a4a27c5483e4850b51ff2e3d8aa7573d879f1257f9b663db5eecb0"
      url "https://github.com/MadAppGang/magmux/releases/download/v#{version}/magmux_linux_amd64.tar.gz"
    end
  end

  name "magmux"
  desc "Minimal terminal multiplexer written in Go. Zero third-party dependencies."
  homepage "https://github.com/MadAppGang/magmux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "magmux"

  postflight do
    # LOAD-BEARING, and measured rather than assumed.
    #
    # The quarantine is not something a Go binary attracts, and it is
    # nothing to do with .app bundles — Gatekeeper enforces
    # com.apple.quarantine on any Mach-O executable. Two separate steps
    # produce it, and only the second is ours:
    #   1. Homebrew quarantines whatever it DOWNLOADS. The tarball in
    #      ~/Library/Caches/Homebrew/downloads already carries the
    #      attribute before anything is extracted.
    #   2. CASKS then copy it onto the extracted payload
    #      (Quarantine.propagate, cask/download.rb:129). FORMULAS never
    #      call it — every call site is under cask/. That difference is
    #      the whole reason this hook did not exist before v0.12.0.
    # Being unsigned is not why the attribute is applied; it is why
    # Gatekeeper then REFUSES the quarantined file.
    # Installing the cask with this hook removed, on a real machine:
    # com.apple.quarantine was set on the staged binary and
    # `magmux --version` printed NOTHING and exited — Gatekeeper killed
    # it silently, which is the worst shape a failure can take because
    # `brew install` still reported success. With the hook, the attribute
    # is absent and the binary runs. The old formula sidestepped this
    # entirely by using bin.install on an already-extracted file.
    #
    # GoReleaser renders this as Homebrew's `postflight`, which Homebrew
    # now warns is deprecated in favour of `postflight_steps`. That
    # warning is GoReleaser's template to fix, not ours, and it is a
    # warning rather than a failure — removing the hook to silence it
    # would trade a visible warning for a silent broken install.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/magmux"]
    end
  end

  # No zap stanza required
end
