# This file was generated by GoReleaser. DO NOT EDIT.
cask "magmux" do
  version "0.12.0"

  on_macos do
    on_arm do
      sha256 "8e053f458d5519cd4e6a90a55c16a8806725459b4117047749dc6e992bfdaecc"
      url "https://github.com/MadAppGang/magmux/releases/download/v#{version}/magmux_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f6230ff0b8fd38f10c2ab4b914a50acb5f2cf2df9fc0021d763ad7c7baa262e1"
      url "https://github.com/MadAppGang/magmux/releases/download/v#{version}/magmux_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a40f8e2b9b8181e642cc876fa908556a52620f43ebe2ab77dd73d3e4da9594bb"
      url "https://github.com/MadAppGang/magmux/releases/download/v#{version}/magmux_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3f3ea55c3fac43a5d77e847ae300888451b6e36104d3de37619ed2f809b6b952"
      url "https://github.com/MadAppGang/magmux/releases/download/v#{version}/magmux_linux_amd64.tar.gz"
    end
  end

  name "magmux"
  desc "Minimal terminal multiplexer written in Go. Zero third-party dependencies."
  homepage "https://github.com/MadAppGang/magmux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "magmux"

  postflight do
    # LOAD-BEARING, and measured rather than assumed.
    #
    # The quarantine is not something a Go binary attracts, and it is
    # nothing to do with .app bundles — Gatekeeper enforces
    # com.apple.quarantine on any Mach-O executable. Two separate steps
    # produce it, and only the second is ours:
    #   1. Homebrew quarantines whatever it DOWNLOADS. The tarball in
    #      ~/Library/Caches/Homebrew/downloads already carries the
    #      attribute before anything is extracted.
    #   2. CASKS then copy it onto the extracted payload
    #      (Quarantine.propagate, cask/download.rb:129). FORMULAS never
    #      call it — every call site is under cask/. That difference is
    #      the whole reason this hook did not exist before v0.12.0.
    # Being unsigned is not why the attribute is applied; it is why
    # Gatekeeper then REFUSES the quarantined file.
    # Installing the cask with this hook removed, on a real machine:
    # com.apple.quarantine was set on the staged binary and
    # `magmux --version` printed NOTHING and exited — Gatekeeper killed
    # it silently, which is the worst shape a failure can take because
    # `brew install` still reported success. With the hook, the attribute
    # is absent and the binary runs. The old formula sidestepped this
    # entirely by using bin.install on an already-extracted file.
    #
    # GoReleaser renders this as Homebrew's `postflight`, which Homebrew
    # now warns is deprecated in favour of `postflight_steps`. That
    # warning is GoReleaser's template to fix, not ours, and it is a
    # warning rather than a failure — removing the hook to silence it
    # would trade a visible warning for a silent broken install.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/magmux"]
    end
  end

  # No zap stanza required
end
