# This file was generated by GoReleaser. DO NOT EDIT.
cask "magmux" do
  version "0.11.0"

  on_macos do
    on_arm do
      sha256 "db78756c46d7bebf58615b6d1858115128886274ce0f58893522f57271e5fc7d"
      url "https://github.com/MadAppGang/magmux/releases/download/v0.11.0/magmux_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "611209e73652cd9191667eb6c7ad81383561b3a2a48950d42558bea54ab594ad"
      url "https://github.com/MadAppGang/magmux/releases/download/v0.11.0/magmux_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b66e288d1f36b33904db4b3d5fcf490ed1c8cff3a90eed889c946f31600ddcf5"
      url "https://github.com/MadAppGang/magmux/releases/download/v0.11.0/magmux_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "029cf67492b17d6bb0cfb5f703f8296c77cb1bdcd146fa78c86f8b05fb73bc92"
      url "https://github.com/MadAppGang/magmux/releases/download/v0.11.0/magmux_linux_amd64.tar.gz"
    end
  end

  name "magmux"
  desc "Minimal terminal multiplexer written in Go. Zero third-party dependencies."
  homepage "https://github.com/MadAppGang/magmux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "magmux"

  postflight do
    # The binaries are not signed or notarized, so macOS quarantines them
    # on download and the first run dies with "cannot be opened because
    # the developer cannot be verified". Stripping the attribute is what
    # the formula's direct bin.install used to sidestep entirely.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/magmux"]
    end
  end

  # No zap stanza required
end
