# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Magmux < Formula
  desc "Minimal terminal multiplexer written in Go. Zero third-party dependencies."
  homepage "https://github.com/MadAppGang/magmux"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MadAppGang/magmux/releases/download/v0.5.1/magmux_darwin_amd64.tar.gz"
      sha256 "3a38315650b59dd7214a86d35ba3b544c7d06d0e4da19558d4de41d4f9a7a57a"

      define_method(:install) do
        bin.install "magmux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MadAppGang/magmux/releases/download/v0.5.1/magmux_darwin_arm64.tar.gz"
      sha256 "9342d06c61d1197bb49faee06b56b1b177ae8533018c50b3419ef0bff0021e99"

      define_method(:install) do
        bin.install "magmux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MadAppGang/magmux/releases/download/v0.5.1/magmux_linux_amd64.tar.gz"
      sha256 "972e9d35a3c5afc1f88811ce118979ca6729d968d5597094f313a80d3abf7b35"
      define_method(:install) do
        bin.install "magmux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MadAppGang/magmux/releases/download/v0.5.1/magmux_linux_arm64.tar.gz"
      sha256 "2e86087342a19106b4f3b4dbfcb8c9d05a5fe7fbad96d4afdd0268d699350d85"
      define_method(:install) do
        bin.install "magmux"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/magmux --version 2>&1", 1)
  end
end
