# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Magmux < Formula
  desc "Minimal terminal multiplexer written in Go. Zero third-party dependencies."
  homepage "https://github.com/MadAppGang/magmux"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MadAppGang/magmux/releases/download/v0.1.0/magmux_darwin_amd64.tar.gz"
      sha256 "14ec29c54ee67779cf1fa0892985fd138162567115d3f5aef038156644bd10c6"

      define_method(:install) do
        bin.install "magmux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MadAppGang/magmux/releases/download/v0.1.0/magmux_darwin_arm64.tar.gz"
      sha256 "4b9f73834ea0321130285dc3c02a436d6da3e20009a2118d8a54ecc1b8efc1ec"

      define_method(:install) do
        bin.install "magmux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MadAppGang/magmux/releases/download/v0.1.0/magmux_linux_amd64.tar.gz"
      sha256 "c09c9b030c2b7a159949eed784c5927809905bf7ce0100eb294d96e7baf2c584"
      define_method(:install) do
        bin.install "magmux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MadAppGang/magmux/releases/download/v0.1.0/magmux_linux_arm64.tar.gz"
      sha256 "a485463208ca09bec7eee2bde64524c4eb514288e02a07839a92ca464efdc6e6"
      define_method(:install) do
        bin.install "magmux"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/magmux --version 2>&1", 1)
  end
end
