# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Magmux < Formula
  desc "Minimal terminal multiplexer written in Go. Zero third-party dependencies."
  homepage "https://github.com/MadAppGang/magmux"
  version "0.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MadAppGang/magmux/releases/download/v0.4.3/magmux_darwin_amd64.tar.gz"
      sha256 "0805e12376a190c30dc012dfc876eff92f83bd732275b914b32ea9ad8c908bc0"

      define_method(:install) do
        bin.install "magmux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MadAppGang/magmux/releases/download/v0.4.3/magmux_darwin_arm64.tar.gz"
      sha256 "89896b6a96d6ba26aa7ceff662e9e67d26ee784337eb5a78acca2716edb3ec55"

      define_method(:install) do
        bin.install "magmux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MadAppGang/magmux/releases/download/v0.4.3/magmux_linux_amd64.tar.gz"
      sha256 "5fca7b9897ff2acba8f83d384c49df547d02bdd3ea7d5269d26efb666f6df729"
      define_method(:install) do
        bin.install "magmux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MadAppGang/magmux/releases/download/v0.4.3/magmux_linux_arm64.tar.gz"
      sha256 "604e60592c662c9a1fc5fb516a11f3384a41e130641a9f8f87f3cdf37f7b4f62"
      define_method(:install) do
        bin.install "magmux"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/magmux --version 2>&1", 1)
  end
end
