# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rpaster < Formula
  desc "Paste clipboard images into remote tmux sessions over SSH"
  homepage "https://github.com/MadAppGang/tmux-copy-image"
  version "0.2.1"
  license "MIT"

  depends_on "pngpaste"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MadAppGang/tmux-copy-image/releases/download/v0.2.1/rpaster_darwin_amd64.tar.gz"
      sha256 "5ca74a66fe686eff79bed6406efdf9cbc2fd39ed0f4a35cbe5133764020428a9"

      define_method(:install) do
        bin.install "rpaster"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MadAppGang/tmux-copy-image/releases/download/v0.2.1/rpaster_darwin_arm64.tar.gz"
      sha256 "ba7e72cb51e8fc539002c1d4bb0656c74130d983f82674391dba0a24ef3800d3"

      define_method(:install) do
        bin.install "rpaster"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MadAppGang/tmux-copy-image/releases/download/v0.2.1/rpaster_linux_amd64.tar.gz"
      sha256 "e246396f77ac00d1e63a601e35d2288795021be68920d03adbcb245e594186de"
      define_method(:install) do
        bin.install "rpaster"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MadAppGang/tmux-copy-image/releases/download/v0.2.1/rpaster_linux_arm64.tar.gz"
      sha256 "bfe31c4c29df0faf3cf748d3580f05e93d5ab5bcc49c8a20099f75598b0b0c83"
      define_method(:install) do
        bin.install "rpaster"
      end
    end
  end

  def caveats
    <<~EOS
      ┌─────────────────────────────────────────────────────┐
      │  rpaster — clipboard image paste over SSH           │
      └─────────────────────────────────────────────────────┘

      Step 1: Start the daemon (runs on login automatically)

        brew services start rpaster

      Step 2: Set up your remote host(s) (plugin + SSH tunnel)

        rpaster install --remote your-remote-host

      Step 3: Use it!

        SSH to your remote, open tmux, copy an image locally,
        then press:  prefix + V

      Verify:    rpaster doctor
      Full docs: https://github.com/MadAppGang/tmux-copy-image
    EOS
  end

  service do
    run [opt_bin/"rpaster", "serve"]
    keep_alive true
    log_path var/"log/rpaster.log"
    error_log_path var/"log/rpaster.log"
  end

  test do
    system "#{bin}/rpaster", "version"
  end
end
