# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rpaster < Formula
  desc "Paste clipboard images into remote tmux sessions over SSH"
  homepage "https://github.com/MadAppGang/tmux-copy-image"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MadAppGang/tmux-copy-image/releases/download/v0.1.2/rpaster_darwin_amd64.tar.gz"
      sha256 "9b140b95b608e9e1da04d90f592c83c1ced937a57d8d519a5ff9b2715655ad1a"

      define_method(:install) do
        bin.install "rpaster"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MadAppGang/tmux-copy-image/releases/download/v0.1.2/rpaster_darwin_arm64.tar.gz"
      sha256 "c87ea69fd248482db9a17eaee54993322f5e05947040a958729d28f9d9ec82c4"

      define_method(:install) do
        bin.install "rpaster"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MadAppGang/tmux-copy-image/releases/download/v0.1.2/rpaster_linux_amd64.tar.gz"
      sha256 "4acc57a02545edb3890a5ea104c40a51f3853ac566db807e593bc2d69a6760ee"
      define_method(:install) do
        bin.install "rpaster"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MadAppGang/tmux-copy-image/releases/download/v0.1.2/rpaster_linux_arm64.tar.gz"
      sha256 "0a7c28aa26bae3275e9995a6f4d42dd9cfb786fb6db7dd46864de0609934bece"
      define_method(:install) do
        bin.install "rpaster"
      end
    end
  end

  service do
    run [opt_bin/"rpaster", "serve"]
    keep_alive true
    log_path var/"log/rpaster.log"
    error_log_path var/"log/rpaster.log"
  end

  test do
    system "#{bin}/rpaster", "version"
  end
end
