# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rpaster < Formula
  desc "Paste clipboard images into remote tmux sessions over SSH"
  homepage "https://github.com/MadAppGang/tmux-copy-image"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MadAppGang/tmux-copy-image/releases/download/v0.1.4/rpaster_darwin_amd64.tar.gz"
      sha256 "b376cf12c753d0bf08c8a032994d29443843787e86dc1d565edaa6297080bb31"

      define_method(:install) do
        bin.install "rpaster"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MadAppGang/tmux-copy-image/releases/download/v0.1.4/rpaster_darwin_arm64.tar.gz"
      sha256 "3a63f87b6f8b5f4de294df6f497af625b92f50498b095fc3b76e6fa5f8e6a9d0"

      define_method(:install) do
        bin.install "rpaster"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MadAppGang/tmux-copy-image/releases/download/v0.1.4/rpaster_linux_amd64.tar.gz"
      sha256 "9c6815036f03d930c0054cf0bde4448607fbb19d7cbb5a926ec0ae5bb4c59d25"
      define_method(:install) do
        bin.install "rpaster"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MadAppGang/tmux-copy-image/releases/download/v0.1.4/rpaster_linux_arm64.tar.gz"
      sha256 "9b6a229eb20b8a41fede66fbfd191b3394d6030125568f98e6ee6cb298e331ba"
      define_method(:install) do
        bin.install "rpaster"
      end
    end
  end

  def caveats
    <<~EOS
      ┌─────────────────────────────────────────────────────┐
      │  rpaster — clipboard image paste over SSH           │
      └─────────────────────────────────────────────────────┘

      Step 1: Start the daemon (runs on login automatically)

        brew services start rpaster

      Step 2: Add SSH tunnel to your remote host(s)

        Add to ~/.ssh/config:

          Host your-remote-host
              RemoteForward 127.0.0.1:18339 127.0.0.1:18339

      Step 3: Install tmux plugin on the remote machine

        rpaster install --remote your-remote-host

        Or manually: https://github.com/MadAppGang/tmux-copy-image#remote-setup

      Step 4: Use it!

        SSH to your remote, open tmux, copy an image locally,
        then press:  prefix + V

      Verify:    rpaster doctor
      Full docs: https://github.com/MadAppGang/tmux-copy-image
    EOS
  end

  service do
    run [opt_bin/"rpaster", "serve"]
    keep_alive true
    log_path var/"log/rpaster.log"
    error_log_path var/"log/rpaster.log"
  end

  test do
    system "#{bin}/rpaster", "version"
  end
end
